HW2/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('all_users/', include('all_users.urls', namespace='all_users')),
    #path('all_users/', include('django.contrib.auth.urls')),
    #path('test/', views.TestPage.as_view(), name='test'),
    path('candidates/', include('candidates.urls', namespace='candidates')),
]

all_users/urls.py
# all_users urls.py

from django.urls import path
from django.contrib.auth import views as auth_views

from all_users import views


app_name = 'all_users'

urlpatterns = [
	path('signup/', views.SignUp.as_view(), name='signup'),
	#path('login/', auth_views.LoginView.as_view(template_name='all_users/login.html'), name='login'),
	path('login/', views.CustomLoginView, name='login'),
	path('test_candidate/', views.TestCandidatePage.as_view(), name='test_candidate'),
	path('test_employer/', views.TestEmployerPage.as_view(), name='test_employer'),
]

candidates/urls.py
from django.urls import path

from candidates import views

app_name = 'candidates'

urlpatterns = [
	path('create/<username>', views.CreateCandidateProfileView.as_view(), name='create'),
	path('profile/<pk:user.pk>', views.CandidateProfileView.as_view(), name='profile-detail'),

]

all_users/models.py
# all_users models.py

from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):

	candidate = 'candidate'
	employer = 'employer'

	user_type_choices = (
		(candidate, 'Candidate'),
		(employer, 'Employer'),
		)

	user_type = models.CharField(
		max_length = 50,
		choices = user_type_choices,
		default = candidate
		)

	#is_candidate = models.BooleanField(default=False)
	#is_employer = models.BooleanField(default=False)

	@property
	def is_candidate(self):
		if self.user_type == 'candidate':
			print(self.username)
			print("user_type is candidate")
			return True
		return False

	@property
	def is_employer(self):
		if self.user_type == 'employer':
			print(self.username)
			print("user_type is employer")
			return True
		return False

candidates/models.py
# candidates models.py

from django.db import models
from django.urls import reverse
from django.db.models.signals import post_save
#from django.dispatch import receiver

from all_users.models import User

class Candidate_Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
	resume = models.FileField(upload_to='resumes/')
	biography = models.TextField()
	LinkedIn = models.URLField(blank=True)
	website = models.URLField(blank=True)

	def __str__(self):
		return self.user.username

	# Need to edit this save method
	# self.user should be the user with the same username
	def save(self):
		pass 

	def get_absolute_url(self):
		return reverse('candidates:profile-detail')


# Everytime a user signs up and choses user type candidate
# it automatically creats a candidate profile
def create_candidate_profile(sender, instance, created, **kwargs):

	if created and instance.is_candidate:
		print("Creating candidate profile")
		Candidate_Profile.objects.create(user=instance)
		print("Candidate profile created.")

post_save.connect(create_candidate_profile, sender=User)

def save_candidate_profile(sender, instance, **kwargs):
	print("Saving candidate profile.")
	instance.candidate_profile.save()
	print("Candidate profile saved.")

post_save.connect(save_candidate_profile, sender=User)

all_users/forms.py
# all_users forms.py

from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth import authenticate

from all_users.models import User

class UserSignUpForm(UserCreationForm):

	class Meta():
		model = User
		fields = ('first_name', 'last_name', 'username', 'email', 'user_type', 'password1', 'password2')

class CustomLoginForm(forms.ModelForm):

	password = forms.CharField(widget=forms.PasswordInput())

	class Meta:
		model = User
		fields = ('username', 'password')

	def clean(self):
		username = self.cleaned_data.get('username')
		password = self.cleaned_data.get('password')
		user = authenticate(username=username, password=password)
		if not user or not user.is_active:
			raise forms.ValidationError("Sorry, the login was invalid. Please try again!")

		return self.cleaned_data

	def login(self, request):
		username = self.cleaned_data.get('username')
		password = self.cleaned_data.get('password')
		user = authenticate(username=username, password=password)
		return user

candidates/forms.py
# candidates forms.py

from django import forms
from candidates.models import Candidate_Profile

class CandidateProfileForm(forms.ModelForm):

	class Meta:
		model = Candidate_Profile
		fields = ('resume','biography','LinkedIn','website')

HW2/views.py
# HW2 views.py
from django.views.generic import TemplateView

class HomePage(TemplateView):
	template_name = 'index.html'

all_users/views.py
# all_users views.py

from django.shortcuts import render, redirect
from django.views.generic import TemplateView, CreateView
from django.urls import reverse, reverse_lazy
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
#from django.contrib.auth.views import LoginView

from all_users.forms import UserSignUpForm, CustomLoginForm

class SignUp(CreateView):
	form_class = UserSignUpForm
	success_url = reverse_lazy('all_users:login')
	template_name = 'all_users/signup.html'

def CustomLoginView(request):
	form = CustomLoginForm(request.POST or None)
	if request.method == 'POST' and form.is_valid():
		user = form.login(request)
		if user:
			if user.is_candidate:
				login(request, user)
				print("user is logged in.")
				return HttpResponseRedirect(reverse('all_users:test_candidate'))
			elif user.is_employer:
				login(request, user)
				print("user is logged in.")
				return HttpResponseRedirect(reverse('all_users:test_employer'))
	return render(request, 'all_users/login.html', {'login_form': form})

class TestCandidatePage(TemplateView):
	template_name = 'all_users/test_candidate.html'

class TestEmployerPage(TemplateView):
	template_name = 'all_users/test_employer.html'

candidates/views.py
# candidates views.py

from django.shortcuts import render
from django.views.generic import FormView, DetailView
from django.urls import reverse_lazy

from candidates.forms import CandidateProfileForm
from candidates.models import Candidate_Profile

class CreateCandidateProfileView(FormView):

	template_name = 'candidates/create_candidate_profile.html'
	form_class = CandidateProfileForm

class CandidateProfileView(DetailView):

	model = Candidate_Profile

all_users/templates/all_users/login.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block body_block %}

<h1>Here is the login page!</h1>

<form method="POST">
	{% csrf_token %}
	{% bootstrap_form login_form %}
	<input type="submit" value="Login" class="btn btn-default">
</form>
{% endblock body_block %}

all_users/templates/all_users/signup.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block body_block %}
	<h1>Sign Up</h1>
		<form method="POST">
			{% csrf_token %}
			{% bootstrap_form form %}
			<input type="submit" name="Sign Up" class="btn btn-default">
		</form>
{% endblock body_block %}

all_users/templates/all_users/test_candidate.html
{% extends "base.html" %}
{% block body_block %}

<h1>Here is the test <strong>candidate</strong> page after logging in.</h1>
<p>{{ user.username }}</p>
<p>{{ user.user_type }}</p>
	
{% endblock body_block %}

all_users/templates/all_users/test_employer.html
{% extends "base.html" %}
{% block body_block %}

<h1>Here is the test <strong>employer</strong> page after logging in.</h1>
<p>{{ user.username }}</p>
<p>{{ user.user_type }}</p>
	
{% endblock body_block %}

candidates/templates/candidates/candidate_profile_detail.html
{% extends "base.html" %}

{% block bodyblock %}
<h1>Profile detail page. Add in later.</h1>
{{ user.username }}
	
{% endblock bodyblock %}

candidates/templates/candidates/create_candidate_profile.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block body_block %}
<h1>Welcome {{ user.first_name }} {{ user.last_name }}! Please create your profile here!</h1>

<form method="POST">
	{% csrf_token %}
	{% bootstrap_form form %}
	<input type="submit" value="Create" class="btn btn-primary">
</form>
	
{% endblock body_block %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
<head>
	<title>Job Site</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<a class="navbar-brand" href="{% url 'home' %}">Navbar</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
			{# Need to add in logic for people who are loged in already #}
			<div class="navbar-nav ml-auto">
				<a class="nav-item nav-link" href="{% url 'all_users:signup' %}">Sign Up</a>
				<a class="nav-item nav-link" href="{% url 'all_users:login' %}">Login</a>
			</div>
		</div>
	</nav>

	<div class="container">
		{% block body_block %}
		
		{% endblock body_block %}
	</div>

	

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block body_block %}
	<h1>Welcome to the home page!</h1>
{% endblock body_block %}

templates/test.html
{% extends "base.html" %}

{% block body_block %}
	<h1>Now you are logged in!!!</h1>
{% endblock body_block %}